import {useEffect,useState} from 'react';
import {backendConfigured} from '../services/config';
import {getSession,signIn,signOut,signUp} from '../services/auth';
import {getServerEntitlements,ServerEntitlement} from '../services/entitlementServer';
import {purchase} from '../services/purchase';
import {track} from '../services/analytics';
import {syncTrustedEntitlements} from '../entitlements';
export default function AccountAccess(){const [session,setSession]=useState(getSession());const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [mode,setMode]=useState<'signin'|'signup'>('signin');const [ents,setEnts]=useState<ServerEntitlement[]>([]);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);
 async function restore(){try{const next=await getServerEntitlements();setEnts(next);await syncTrustedEntitlements();}catch(e){await syncTrustedEntitlements();setMsg(e instanceof Error?e.message:'Unable to restore purchases.')}}
 useEffect(()=>{if(session)restore()},[session]);
 async function submit(){setBusy(true);setMsg('');try{const d=mode==='signin'?await signIn(email,password):await signUp(email,password);setSession(getSession());if(mode==='signup'&&!d.access_token)setMsg('Account created. Check your email if confirmation is required.');else{setMsg('Signed in.');void 0}}catch(e){setMsg(e instanceof Error?e.message:'Authentication failed.')}finally{setBusy(false)}}
 async function buy(sku:'REPORT_399'|'INVESTOR_1499'){setBusy(true);setMsg('');try{track('report_offer_viewed',{sku});track('payment_started',{sku});await purchase(sku,session?.user.email);track('payment_succeeded',{sku});await restore();setMsg('Payment verified. Access restored on this account.')}catch(e){setMsg(e instanceof Error?e.message:'Payment failed.')}finally{setBusy(false)}}
 if(!backendConfigured)return <div className="bg-field-card border border-field-line rounded-xl p-4"><p className="text-field-text font-semibold">Account & purchases</p><p className="text-field-muted text-xs mt-1">Local field workflow is available. Production account services activate after secure backend configuration.</p></div>;
 return <div className="bg-field-card border border-field-line rounded-xl p-4 space-y-3"><div><p className="text-field-text font-semibold">Account & purchases</p><p className="text-field-muted text-xs">Property dossiers and evidence stay on this device. Account data is used only for purchase entitlement.</p></div>{msg&&<p className="text-xs text-field-accent">{msg}</p>}{!session?<><div className="flex gap-1 bg-field-panel border border-field-line rounded-lg p-1"><button className={`flex-1 rounded-md py-2 text-sm font-medium ${mode==='signin'?'bg-field-card text-field-text':'text-field-muted'}`} onClick={()=>setMode('signin')}>Sign in</button><button className={`flex-1 rounded-md py-2 text-sm font-medium ${mode==='signup'?'bg-field-card text-field-text':'text-field-muted'}`} onClick={()=>setMode('signup')}>Create account</button></div><input className="w-full bg-field-panel border border-field-line rounded-lg p-3" type="email" autoComplete="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="w-full bg-field-panel border border-field-line rounded-lg p-3" type="password" autoComplete={mode==='signin'?'current-password':'new-password'} placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy||!email||password.length<8} onClick={submit} className="w-full bg-field-accent text-field-bg rounded-lg py-3 font-semibold disabled:opacity-40">{busy?'Please wait…':mode==='signin'?'Sign in':'Create account'}</button></>:<><div className="rounded-lg bg-field-panel border border-field-line p-3"><p className="text-sm text-field-text">{session.user.email||'Signed-in account'}</p><p className="text-[11px] text-field-muted">{ents.length?`${ents.length} active purchase entitlement${ents.length===1?'':'s'}`:'No active paid entitlement found.'}</p></div><div className="grid grid-cols-2 gap-2"><button disabled={busy} onClick={()=>buy('REPORT_399')} className="border border-field-accent text-field-accent rounded-lg p-3 text-sm">Report · ₹399</button><button disabled={busy} onClick={()=>buy('INVESTOR_1499')} className="bg-field-accent text-field-bg rounded-lg p-3 text-sm font-semibold">Investor · ₹1,499/yr</button></div><div className="flex gap-2"><button disabled={busy} onClick={restore} className="flex-1 border border-field-line rounded-lg py-2 text-xs">Restore purchases</button><button onClick={async()=>{await signOut();setSession(null);setEnts([]);await syncTrustedEntitlements();setMsg('Signed out.')}} className="flex-1 border border-field-line rounded-lg py-2 text-xs">Sign out</button></div></>}</div>}
